//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Readers.Generated
{ 
// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
[XmlRoot("mzML", Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
public partial class mzMLType {
    
    private CVListType cvListField;
    
    private FileDescriptionType fileDescriptionField;
    
    private ReferenceableParamGroupListType referenceableParamGroupListField;
    
    private SampleListType sampleListField;
    
    private SoftwareListType softwareListField;
    
    private ScanSettingsListType scanSettingsListField;
    
    private InstrumentConfigurationListType instrumentConfigurationListField;
    
    private DataProcessingListType dataProcessingListField;
    
    private RunType runField;
    
    private string accessionField;
    
    private string versionField;
    
    private string idField;
    
    /// <remarks/>
    public CVListType cvList {
        get {
            return this.cvListField;
        }
        set {
            this.cvListField = value;
        }
    }
    
    /// <remarks/>
    public FileDescriptionType fileDescription {
        get {
            return this.fileDescriptionField;
        }
        set {
            this.fileDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public ReferenceableParamGroupListType referenceableParamGroupList {
        get {
            return this.referenceableParamGroupListField;
        }
        set {
            this.referenceableParamGroupListField = value;
        }
    }
    
    /// <remarks/>
    public SampleListType sampleList {
        get {
            return this.sampleListField;
        }
        set {
            this.sampleListField = value;
        }
    }
    
    /// <remarks/>
    public SoftwareListType softwareList {
        get {
            return this.softwareListField;
        }
        set {
            this.softwareListField = value;
        }
    }
    
    /// <remarks/>
    public ScanSettingsListType scanSettingsList {
        get {
            return this.scanSettingsListField;
        }
        set {
            this.scanSettingsListField = value;
        }
    }
    
    /// <remarks/>
    public InstrumentConfigurationListType instrumentConfigurationList {
        get {
            return this.instrumentConfigurationListField;
        }
        set {
            this.instrumentConfigurationListField = value;
        }
    }
    
    /// <remarks/>
    public DataProcessingListType dataProcessingList {
        get {
            return this.dataProcessingListField;
        }
        set {
            this.dataProcessingListField = value;
        }
    }
    
    /// <remarks/>
    public RunType run {
        get {
            return this.runField;
        }
        set {
            this.runField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string accession {
        get {
            return this.accessionField;
        }
        set {
            this.accessionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class CVListType {
    
    private CVType[] cvField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("cv")]
    public CVType[] cv {
        get {
            return this.cvField;
        }
        set {
            this.cvField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class CVType {
    
    private string idField;
    
    private string fullNameField;
    
    private string versionField;
    
    private string uRIField;
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string fullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string URI {
        get {
            return this.uRIField;
        }
        set {
            this.uRIField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class OffsetType {
    
    private string idRefField;
    
    private string spotIDField;
    
    private double scanTimeField;
    
    private bool scanTimeFieldSpecified;
    
    private long valueField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string idRef {
        get {
            return this.idRefField;
        }
        set {
            this.idRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string spotID {
        get {
            return this.spotIDField;
        }
        set {
            this.spotIDField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public double scanTime {
        get {
            return this.scanTimeField;
        }
        set {
            this.scanTimeField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool scanTimeSpecified {
        get {
            return this.scanTimeFieldSpecified;
        }
        set {
            this.scanTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [XmlText()]
    public long Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class IndexType {
    
    private OffsetType[] offsetField;
    
    private IndexTypeName nameField;
    
    /// <remarks/>
    [XmlElement("offset")]
    public OffsetType[] offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public IndexTypeName name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[XmlType(AnonymousType=true, Namespace="http://psi.hupo.org/ms/mzml")]
public enum IndexTypeName {
    
    /// <remarks/>
    spectrum,
    
    /// <remarks/>
    chromatogram,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class IndexListType {
    
    private IndexType[] indexField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("index")]
    public IndexType[] index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class DataProcessingType {
    
    private ProcessingMethodType[] processingMethodField;
    
    private string idField;
    
    /// <remarks/>
    [XmlElement("processingMethod")]
    public ProcessingMethodType[] processingMethod {
        get {
            return this.processingMethodField;
        }
        set {
            this.processingMethodField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ProcessingMethodType : ParamGroupType {
    
    private string orderField;
    
    private string softwareRefField;
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string softwareRef {
        get {
            return this.softwareRefField;
        }
        set {
            this.softwareRefField = value;
        }
    }
}

/// <remarks/>
[XmlInclude(typeof(ChromatogramType))]
[XmlInclude(typeof(BinaryDataArrayType))]
[XmlInclude(typeof(ScanType))]
[XmlInclude(typeof(ScanListType))]
[XmlInclude(typeof(SpectrumType))]
[XmlInclude(typeof(RunType))]
[XmlInclude(typeof(ScanSettingsType))]
[XmlInclude(typeof(ProcessingMethodType))]
[XmlInclude(typeof(SoftwareType))]
[XmlInclude(typeof(InstrumentConfigurationType))]
[XmlInclude(typeof(ComponentType))]
[XmlInclude(typeof(AnalyzerComponentType))]
[XmlInclude(typeof(DetectorComponentType))]
[XmlInclude(typeof(SourceComponentType))]
[XmlInclude(typeof(SampleType))]
[XmlInclude(typeof(SourceFileType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ParamGroupType {
    
    private ReferenceableParamGroupRefType[] referenceableParamGroupRefField;
    
    private CVParamType[] cvParamField;
    
    private UserParamType[] userParamField;
    
    /// <remarks/>
    [XmlElement("referenceableParamGroupRef")]
    public ReferenceableParamGroupRefType[] referenceableParamGroupRef {
        get {
            return this.referenceableParamGroupRefField;
        }
        set {
            this.referenceableParamGroupRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("cvParam")]
    public CVParamType[] cvParam {
        get {
            return this.cvParamField;
        }
        set {
            this.cvParamField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("userParam")]
    public UserParamType[] userParam {
        get {
            return this.userParamField;
        }
        set {
            this.userParamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ReferenceableParamGroupRefType {
    
    private string refField;
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class CVParamType {
    
    private string cvRefField;
    
    private string accessionField;
    
    private string valueField;
    
    private string nameField;
    
    private string unitAccessionField;
    
    private string unitNameField;
    
    private string unitCvRefField;
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string cvRef {
        get {
            return this.cvRefField;
        }
        set {
            this.cvRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string accession {
        get {
            return this.accessionField;
        }
        set {
            this.accessionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string unitAccession {
        get {
            return this.unitAccessionField;
        }
        set {
            this.unitAccessionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string unitName {
        get {
            return this.unitNameField;
        }
        set {
            this.unitNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string unitCvRef {
        get {
            return this.unitCvRefField;
        }
        set {
            this.unitCvRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class UserParamType {
    
    private string nameField;
    
    private string typeField;
    
    private string valueField;
    
    private string unitAccessionField;
    
    private string unitNameField;
    
    private string unitCvRefField;
    
    /// <remarks/>
    [XmlAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string unitAccession {
        get {
            return this.unitAccessionField;
        }
        set {
            this.unitAccessionField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string unitName {
        get {
            return this.unitNameField;
        }
        set {
            this.unitNameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string unitCvRef {
        get {
            return this.unitCvRefField;
        }
        set {
            this.unitCvRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ChromatogramType : ParamGroupType {
    
    private PrecursorType precursorField;
    
    private ProductType productField;
    
    private BinaryDataArrayListType binaryDataArrayListField;
    
    private string idField;
    
    private string indexField;
    
    private int defaultArrayLengthField;
    
    private string dataProcessingRefField;
    
    /// <remarks/>
    public PrecursorType precursor {
        get {
            return this.precursorField;
        }
        set {
            this.precursorField = value;
        }
    }
    
    /// <remarks/>
    public ProductType product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    public BinaryDataArrayListType binaryDataArrayList {
        get {
            return this.binaryDataArrayListField;
        }
        set {
            this.binaryDataArrayListField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public int defaultArrayLength {
        get {
            return this.defaultArrayLengthField;
        }
        set {
            this.defaultArrayLengthField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string dataProcessingRef {
        get {
            return this.dataProcessingRefField;
        }
        set {
            this.dataProcessingRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class PrecursorType {
    
    private ParamGroupType isolationWindowField;
    
    private SelectedIonListType selectedIonListField;
    
    private ParamGroupType activationField;
    
    private string spectrumRefField;
    
    private string sourceFileRefField;
    
    private string externalSpectrumIDField;
    
    /// <remarks/>
    public ParamGroupType isolationWindow {
        get {
            return this.isolationWindowField;
        }
        set {
            this.isolationWindowField = value;
        }
    }
    
    /// <remarks/>
    public SelectedIonListType selectedIonList {
        get {
            return this.selectedIonListField;
        }
        set {
            this.selectedIonListField = value;
        }
    }
    
    /// <remarks/>
    public ParamGroupType activation {
        get {
            return this.activationField;
        }
        set {
            this.activationField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string spectrumRef {
        get {
            return this.spectrumRefField;
        }
        set {
            this.spectrumRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string sourceFileRef {
        get {
            return this.sourceFileRefField;
        }
        set {
            this.sourceFileRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string externalSpectrumID {
        get {
            return this.externalSpectrumIDField;
        }
        set {
            this.externalSpectrumIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SelectedIonListType {
    
    private ParamGroupType[] selectedIonField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("selectedIon")]
    public ParamGroupType[] selectedIon {
        get {
            return this.selectedIonField;
        }
        set {
            this.selectedIonField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ProductType {
    
    private ParamGroupType isolationWindowField;
    
    /// <remarks/>
    public ParamGroupType isolationWindow {
        get {
            return this.isolationWindowField;
        }
        set {
            this.isolationWindowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class BinaryDataArrayListType {
    
    private BinaryDataArrayType[] binaryDataArrayField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("binaryDataArray")]
    public BinaryDataArrayType[] binaryDataArray {
        get {
            return this.binaryDataArrayField;
        }
        set {
            this.binaryDataArrayField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class BinaryDataArrayType : ParamGroupType {
    
    private byte[] binaryField;
    
    private string arrayLengthField;
    
    private string dataProcessingRefField;
    
    private string encodedLengthField;
    
    /// <remarks/>
    [XmlElement(DataType="base64Binary")]
    public byte[] binary {
        get {
            return this.binaryField;
        }
        set {
            this.binaryField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string arrayLength {
        get {
            return this.arrayLengthField;
        }
        set {
            this.arrayLengthField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string dataProcessingRef {
        get {
            return this.dataProcessingRefField;
        }
        set {
            this.dataProcessingRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string encodedLength {
        get {
            return this.encodedLengthField;
        }
        set {
            this.encodedLengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ScanType : ParamGroupType {
    
    private ScanWindowListType scanWindowListField;
    
    private string spectrumRefField;
    
    private string sourceFileRefField;
    
    private string externalSpectrumIDField;
    
    private string instrumentConfigurationRefField;
    
    /// <remarks/>
    public ScanWindowListType scanWindowList {
        get {
            return this.scanWindowListField;
        }
        set {
            this.scanWindowListField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string spectrumRef {
        get {
            return this.spectrumRefField;
        }
        set {
            this.spectrumRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string sourceFileRef {
        get {
            return this.sourceFileRefField;
        }
        set {
            this.sourceFileRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string externalSpectrumID {
        get {
            return this.externalSpectrumIDField;
        }
        set {
            this.externalSpectrumIDField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string instrumentConfigurationRef {
        get {
            return this.instrumentConfigurationRefField;
        }
        set {
            this.instrumentConfigurationRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ScanWindowListType {
    
    private ParamGroupType[] scanWindowField;
    
    private int countField;
    
    /// <remarks/>
    [XmlElement("scanWindow")]
    public ParamGroupType[] scanWindow {
        get {
            return this.scanWindowField;
        }
        set {
            this.scanWindowField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public int count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ScanListType : ParamGroupType {
    
    private ScanType[] scanField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("scan")]
    public ScanType[] scan {
        get {
            return this.scanField;
        }
        set {
            this.scanField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SpectrumType : ParamGroupType {
    
    private ScanListType scanListField;
    
    private PrecursorListType precursorListField;
    
    private ProductListType productListField;
    
    private BinaryDataArrayListType binaryDataArrayListField;
    
    private string idField;
    
    private string spotIDField;
    
    private string indexField;
    
    private int defaultArrayLengthField;
    
    private string dataProcessingRefField;
    
    private string sourceFileRefField;
    
    /// <remarks/>
    public ScanListType scanList {
        get {
            return this.scanListField;
        }
        set {
            this.scanListField = value;
        }
    }
    
    /// <remarks/>
    public PrecursorListType precursorList {
        get {
            return this.precursorListField;
        }
        set {
            this.precursorListField = value;
        }
    }
    
    /// <remarks/>
    public ProductListType productList {
        get {
            return this.productListField;
        }
        set {
            this.productListField = value;
        }
    }
    
    /// <remarks/>
    public BinaryDataArrayListType binaryDataArrayList {
        get {
            return this.binaryDataArrayListField;
        }
        set {
            this.binaryDataArrayListField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string spotID {
        get {
            return this.spotIDField;
        }
        set {
            this.spotIDField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public int defaultArrayLength {
        get {
            return this.defaultArrayLengthField;
        }
        set {
            this.defaultArrayLengthField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string dataProcessingRef {
        get {
            return this.dataProcessingRefField;
        }
        set {
            this.dataProcessingRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string sourceFileRef {
        get {
            return this.sourceFileRefField;
        }
        set {
            this.sourceFileRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class PrecursorListType {
    
    private PrecursorType[] precursorField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("precursor")]
    public PrecursorType[] precursor {
        get {
            return this.precursorField;
        }
        set {
            this.precursorField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ProductListType {
    
    private ProductType[] productField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("product")]
    public ProductType[] product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class RunType : ParamGroupType {
    
    private SpectrumListType spectrumListField;
    
    private ChromatogramListType chromatogramListField;
    
    private string idField;
    
    private string defaultInstrumentConfigurationRefField;
    
    private string defaultSourceFileRefField;
    
    private string sampleRefField;
    
    private System.DateTime startTimeStampField;
    
    private bool startTimeStampFieldSpecified;
    
    /// <remarks/>
    public SpectrumListType spectrumList {
        get {
            return this.spectrumListField;
        }
        set {
            this.spectrumListField = value;
        }
    }
    
    /// <remarks/>
    public ChromatogramListType chromatogramList {
        get {
            return this.chromatogramListField;
        }
        set {
            this.chromatogramListField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string defaultInstrumentConfigurationRef {
        get {
            return this.defaultInstrumentConfigurationRefField;
        }
        set {
            this.defaultInstrumentConfigurationRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string defaultSourceFileRef {
        get {
            return this.defaultSourceFileRefField;
        }
        set {
            this.defaultSourceFileRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string sampleRef {
        get {
            return this.sampleRefField;
        }
        set {
            this.sampleRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public System.DateTime startTimeStamp {
        get {
            return this.startTimeStampField;
        }
        set {
            this.startTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [XmlIgnore()]
    public bool startTimeStampSpecified {
        get {
            return this.startTimeStampFieldSpecified;
        }
        set {
            this.startTimeStampFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SpectrumListType {
    
    private SpectrumType[] spectrumField;
    
    private string countField;
    
    private string defaultDataProcessingRefField;
    
    /// <remarks/>
    [XmlElement("spectrum")]
    public SpectrumType[] spectrum {
        get {
            return this.spectrumField;
        }
        set {
            this.spectrumField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string defaultDataProcessingRef {
        get {
            return this.defaultDataProcessingRefField;
        }
        set {
            this.defaultDataProcessingRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ChromatogramListType {
    
    private ChromatogramType[] chromatogramField;
    
    private string countField;
    
    private string defaultDataProcessingRefField;
    
    /// <remarks/>
    [XmlElement("chromatogram")]
    public ChromatogramType[] chromatogram {
        get {
            return this.chromatogramField;
        }
        set {
            this.chromatogramField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string defaultDataProcessingRef {
        get {
            return this.defaultDataProcessingRefField;
        }
        set {
            this.defaultDataProcessingRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ScanSettingsType : ParamGroupType {
    
    private SourceFileRefListType sourceFileRefListField;
    
    private TargetListType targetListField;
    
    private string idField;
    
    /// <remarks/>
    public SourceFileRefListType sourceFileRefList {
        get {
            return this.sourceFileRefListField;
        }
        set {
            this.sourceFileRefListField = value;
        }
    }
    
    /// <remarks/>
    public TargetListType targetList {
        get {
            return this.targetListField;
        }
        set {
            this.targetListField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SourceFileRefListType {
    
    private SourceFileRefType[] sourceFileRefField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("sourceFileRef")]
    public SourceFileRefType[] sourceFileRef {
        get {
            return this.sourceFileRefField;
        }
        set {
            this.sourceFileRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SourceFileRefType {
    
    private string refField;
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class TargetListType {
    
    private ParamGroupType[] targetField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("target")]
    public ParamGroupType[] target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SoftwareType : ParamGroupType {
    
    private string idField;
    
    private string versionField;
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class InstrumentConfigurationType : ParamGroupType {
    
    private ComponentListType componentListField;
    
    private SoftwareRefType softwareRefField;
    
    private string idField;
    
    private string scanSettingsRefField;
    
    /// <remarks/>
    public ComponentListType componentList {
        get {
            return this.componentListField;
        }
        set {
            this.componentListField = value;
        }
    }
    
    /// <remarks/>
    public SoftwareRefType softwareRef {
        get {
            return this.softwareRefField;
        }
        set {
            this.softwareRefField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string scanSettingsRef {
        get {
            return this.scanSettingsRefField;
        }
        set {
            this.scanSettingsRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ComponentListType {
    
    private SourceComponentType[] sourceField;
    
    private AnalyzerComponentType[] analyzerField;
    
    private DetectorComponentType[] detectorField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("source")]
    public SourceComponentType[] source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("analyzer")]
    public AnalyzerComponentType[] analyzer {
        get {
            return this.analyzerField;
        }
        set {
            this.analyzerField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("detector")]
    public DetectorComponentType[] detector {
        get {
            return this.detectorField;
        }
        set {
            this.detectorField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SourceComponentType : ComponentType {
}

/// <remarks/>
[XmlInclude(typeof(AnalyzerComponentType))]
[XmlInclude(typeof(DetectorComponentType))]
[XmlInclude(typeof(SourceComponentType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ComponentType : ParamGroupType {
    
    private int orderField;
    
    /// <remarks/>
    [XmlAttribute()]
    public int order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class AnalyzerComponentType : ComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class DetectorComponentType : ComponentType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SoftwareRefType {
    
    private string refField;
    
    /// <remarks/>
    [XmlAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SampleType : ParamGroupType {
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SourceFileType : ParamGroupType {
    
    private string idField;
    
    private string nameField;
    
    private string locationField;
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="anyURI")]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class DataProcessingListType {
    
    private DataProcessingType[] dataProcessingField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("dataProcessing")]
    public DataProcessingType[] dataProcessing {
        get {
            return this.dataProcessingField;
        }
        set {
            this.dataProcessingField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class InstrumentConfigurationListType {
    
    private InstrumentConfigurationType[] instrumentConfigurationField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("instrumentConfiguration")]
    public InstrumentConfigurationType[] instrumentConfiguration {
        get {
            return this.instrumentConfigurationField;
        }
        set {
            this.instrumentConfigurationField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ScanSettingsListType {
    
    private ScanSettingsType[] scanSettingsField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("scanSettings")]
    public ScanSettingsType[] scanSettings {
        get {
            return this.scanSettingsField;
        }
        set {
            this.scanSettingsField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SoftwareListType {
    
    private SoftwareType[] softwareField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("software")]
    public SoftwareType[] software {
        get {
            return this.softwareField;
        }
        set {
            this.softwareField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SampleListType {
    
    private SampleType[] sampleField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("sample")]
    public SampleType[] sample {
        get {
            return this.sampleField;
        }
        set {
            this.sampleField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ReferenceableParamGroupType {
    
    private CVParamType[] cvParamField;
    
    private UserParamType[] userParamField;
    
    private string idField;
    
    /// <remarks/>
    [XmlElement("cvParam")]
    public CVParamType[] cvParam {
        get {
            return this.cvParamField;
        }
        set {
            this.cvParamField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("userParam")]
    public UserParamType[] userParam {
        get {
            return this.userParamField;
        }
        set {
            this.userParamField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class ReferenceableParamGroupListType {
    
    private ReferenceableParamGroupType[] referenceableParamGroupField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("referenceableParamGroup")]
    public ReferenceableParamGroupType[] referenceableParamGroup {
        get {
            return this.referenceableParamGroupField;
        }
        set {
            this.referenceableParamGroupField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class SourceFileListType {
    
    private SourceFileType[] sourceFileField;
    
    private string countField;
    
    /// <remarks/>
    [XmlElement("sourceFile")]
    public SourceFileType[] sourceFile {
        get {
            return this.sourceFileField;
        }
        set {
            this.sourceFileField = value;
        }
    }
    
    /// <remarks/>
    [XmlAttribute(DataType="nonNegativeInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(Namespace="http://psi.hupo.org/ms/mzml")]
public partial class FileDescriptionType {
    
    private ParamGroupType fileContentField;
    
    private SourceFileListType sourceFileListField;
    
    private ParamGroupType[] contactField;
    
    /// <remarks/>
    public ParamGroupType fileContent {
        get {
            return this.fileContentField;
        }
        set {
            this.fileContentField = value;
        }
    }
    
    /// <remarks/>
    public SourceFileListType sourceFileList {
        get {
            return this.sourceFileListField;
        }
        set {
            this.sourceFileListField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement("contact")]
    public ParamGroupType[] contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlType(AnonymousType=true, Namespace="http://psi.hupo.org/ms/mzml")]
[XmlRoot(Namespace="http://psi.hupo.org/ms/mzml", IsNullable=false)]
public partial class indexedmzML {
    
    private mzMLType mzMLField;
    
    private IndexListType indexListField;
    
    private System.Nullable<long> indexListOffsetField;
    
    private string fileChecksumField;
    
    /// <remarks/>
    public mzMLType mzML {
        get {
            return this.mzMLField;
        }
        set {
            this.mzMLField = value;
        }
    }
    
    /// <remarks/>
    public IndexListType indexList {
        get {
            return this.indexListField;
        }
        set {
            this.indexListField = value;
        }
    }
    
    /// <remarks/>
    [XmlElement(IsNullable=true)]
    public System.Nullable<long> indexListOffset {
        get {
            return this.indexListOffsetField;
        }
        set {
            this.indexListOffsetField = value;
        }
    }
    
    /// <remarks/>
    public string fileChecksum {
        get {
            return this.fileChecksumField;
        }
        set {
            this.fileChecksumField = value;
        }
    }
}
}