<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsefulProteomicsDatabases\UsefulProteomicsDatabases.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="views.sql" LogicalName="OrthologyStore.views.sql" />
  </ItemGroup>

</Project>
