using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Chemistry;
using Easy.Common.Extensions;
using MassSpectrometry.Deconvolution.Parameters;
using MassSpectrometry.Deconvolution;
using MassSpectrometry.Proteomics;
using MassSpectrometry.Proteomics.ProteolyticDigestion;
using MzLibUtil;

namespace MassSpectrometry.Deconvolution.Algorithms
{
    public class SpectralDeconvolutionAlgorithm : DeconvolutionAlgorithm
    {
        // TODO: Make a charge state envelope class, complete with "MostAbundantChargeState"
        public Dictionary<PeptideWithSetModifications, List<IsotopicEnvelope>> EnvelopeDictionary { get; private set; }

        // Consider defining this as a jagged array to increase performance
        public List<MinimalSpectrum>[,] IndexedLibrarySpectra { get; private set; }
        // SpectrumIndexToPwsmMap maps the location of each spectrum within IndexedLibrarySpectra to its respective PeptideWithSetMods and charge
        public Dictionary<(int, int, int), PeptideWithSetModifications> SpectrumIndexToPwsmMap { get; private set; }
        public int MaxThreads; // This should be in the Parameters abstract 
        public SpectralDeconvolutionParameters SpectralParams { get; }
        public PpmTolerance PpmTolerance { get; }

        public SpectralDeconvolutionAlgorithm(SpectralDeconvolutionParameters parameters) : base(parameters)
        {
            var deconvolutionParameters = DeconvolutionParameters as SpectralDeconvolutionParameters;
            if (deconvolutionParameters == null)
            {
                throw new MzLibException(
                    "Improper Deconvolution Parameters were pass to the SpectralDeconvolutionAlgorithm");
            }
            else
            {
                SpectralParams = deconvolutionParameters;
            }

            PpmTolerance = new PpmTolerance(parameters.DeconvolutionTolerancePpm);

            FindLibraryEnvelopes();
            IndexEnvelopes();

        }

        public override IEnumerable<IsotopicEnvelope> Deconvolute(MzSpectrum spectrum)
        {

            if (spectrum == null || spectrum.Size == 0)
            {
                yield break;
            } 

            // For each charge state (key) store the indices corresponding to every potential isotopic envelope (value)
            Dictionary<int, List<List<int>>> potentialEnvelopes = FindPotentialEnvelopes(spectrum);

            // iterate through charge states (potentially not necessary/performant. Could flatten)
            foreach (var keyValuePair in potentialEnvelopes)
            {
                int chargeBinIndex = keyValuePair.Key - SpectralParams.MinAssumedChargeState;
                // iterate through potential envelopes
                foreach (var envelopeIndices in keyValuePair.Value)
                {
                    double mostAbundantMass =  GetMostAbundantMass(spectrum, envelopeIndices);
                    int massBinIndex = (int)Math.Floor((mostAbundantMass - SpectralParams.ScanRange.Minimum) *
                                                   SpectralParams.BinsPerDalton);

                    // Score against matching theoretical envelopes
                    foreach (MinimalSpectrum librarySpectrum in IndexedLibrarySpectra[massBinIndex, chargeBinIndex])
                    {
                        // Score Strategy goes here
                    }
                }
            }


            throw new NotImplementedException();
        }

        /// <summary>
        /// Small helper function to take in an MzSpectrum and a list of indices defining an isotopic envelope
        /// and return the mass to charge ratio for the most intense peak in that envelope
        /// </summary>
        /// <param name="spectrum">An MzSpectrum</param>
        /// <param name="envelopeIndices"> List of indices as generated by the FindPotentialEnvelopesMethod </param>
        /// <returns></returns>
        private static double GetMostAbundantMass(MzSpectrum spectrum, List<int> envelopeIndices)
        {
            double mostIntenseMass = 0;
            double maxIntensity = 0;
            foreach (int i in envelopeIndices)
            {
                if (spectrum.YArray[i] > maxIntensity)
                {
                    maxIntensity = spectrum.YArray[i];
                    mostIntenseMass = spectrum.XArray[i];
                }
            }
            return mostIntenseMass;
        }

        /// <summary>
        /// Populates the EnvelopeDictionary by digesting each protein in the parameters into PeptideWithSetMods,
        /// then calculating an isotopic envelope for each charge state from min to max assumed charge state
        /// </summary>
        private void FindLibraryEnvelopes()
        {
            EnvelopeDictionary = new();
            

            //TODO: Parallelize this section of the code
            foreach (Protein protein in SpectralParams.Proteins)
            {
                // I'm not sure if calling protein.Digest within the foreach statement would call the method anew for every loop
                IEnumerable<PeptideWithSetModifications> uniquePeptides = protein.Digest(
                    SpectralParams.DigestionParams, SpectralParams.FixedModifications,
                    SpectralParams.VariableModifications, SpectralParams.SilacLabels,
                    topDownTruncationSearch: SpectralParams.FindTopDownTruncationProducts);

                foreach (PeptideWithSetModifications pwsm in uniquePeptides)
                {
                    EnvelopeDictionary.Add(pwsm, new List<IsotopicEnvelope>());
                    IsotopicDistribution pwsmDistribution = IsotopicDistribution.GetDistribution(pwsm.FullChemicalFormula,
                        fineResolution: SpectralParams.FineResolutionForIsotopicDistribution,
                        minProbability: SpectralParams.MinProbabilityForIsotopicDistribution);

                    // iterates through all possible charge states, from largest to smallest.
                    // Any isotopic envelope whose most abundant peak would fall within the scan range is written to the envelope dictionary
                    // Once the mass to charge ratio of the most abundant peak is greater than the scan range maximum, the loop breaks
                    for (int charge = SpectralParams.MaxAssumedChargeState;
                         charge >= SpectralParams.MinAssumedChargeState;
                         charge--)
                    {
                        double theoreticalMz = pwsm.MostAbundantMass.ToMz(charge);
                        if (SpectralParams.ScanRange.Contains(theoreticalMz))
                        {
                            EnvelopeDictionary[pwsm].Add(new 
                                IsotopicEnvelope(pwsmDistribution, charge, SpectralParams.AmbiguityThresholdForIsotopicDistribution));
                        }
                        else if (SpectralParams.ScanRange.CompareTo(theoreticalMz) < 0)
                        {
                            break;
                        }
                    }
                }

            }
        }

        /// <summary>
        /// For each envelope in Envelope Dictionary, TODO: Finish this comment
        /// </summary>
        private void IndexEnvelopes()
        {

            int numberOfBinsForIndexing = (int) (SpectralParams.ScanRange.Width * SpectralParams.BinsPerDalton).Ceiling(0);
            IndexedLibrarySpectra = new List<MinimalSpectrum>[numberOfBinsForIndexing,
                SpectralParams.MaxAssumedChargeState + 1 - SpectralParams.MinAssumedChargeState];
            SpectrumIndexToPwsmMap = new();

            foreach (var keyValuePair in EnvelopeDictionary)
            {
                foreach (IsotopicEnvelope envelope in keyValuePair.Value)
                {
                    int massBinIndex = (int)Math.Floor((envelope.MostAbundantObservedIsotopicMz - SpectralParams.ScanRange.Minimum) * 
                                                     SpectralParams.BinsPerDalton);
                    int chargeBinIndex = envelope.Charge - SpectralParams.MinAssumedChargeState;
                    if (IndexedLibrarySpectra[massBinIndex, chargeBinIndex] == null)
                    {
                        IndexedLibrarySpectra[massBinIndex, chargeBinIndex] = new();
                    }
                    MinimalSpectrum envelopeMinimalSpectrum = new MinimalSpectrum(envelope.MzArray, envelope.IntensityArray, envelope.Charge);
                    IndexedLibrarySpectra[massBinIndex, chargeBinIndex].Add(envelopeMinimalSpectrum);
                    SpectrumIndexToPwsmMap.Add(
                        (massBinIndex, chargeBinIndex, IndexedLibrarySpectra[massBinIndex, chargeBinIndex].Count - 1), // tuple consisting of bin index (mass, charge) and list position of MinimalSpectrum object
                        keyValuePair.Key // tuple consisting of PeptideWithSetMods and charge state
                        );

                    // In situations where the most abundant isotope frequency is close to the second most abundant isotope's frequency
                    // ( ratio >= IsotopicEnvelope.AmbiguityRatioMinimum), 
                    // The Spectrum is stored in the index of the second most abundant isotope as well
                    if(envelope.SecondMostAbundantObservedIsotopicMz > 0 )
                    {
                        // Ceiling or floor????
                        int secondBinIndex = (int)Math.Floor( 
                            ((double)envelope.SecondMostAbundantObservedIsotopicMz - SpectralParams.ScanRange.Minimum ) * SpectralParams.BinsPerDalton);
                        if (secondBinIndex != massBinIndex)
                        {
                            if (IndexedLibrarySpectra[secondBinIndex, chargeBinIndex] == null) IndexedLibrarySpectra[secondBinIndex, chargeBinIndex] = new();
                            IndexedLibrarySpectra[secondBinIndex, chargeBinIndex].Add(envelopeMinimalSpectrum);
                            SpectrumIndexToPwsmMap.Add(
                                (secondBinIndex, chargeBinIndex, IndexedLibrarySpectra[secondBinIndex, chargeBinIndex].Count - 1),
                                keyValuePair.Key
                            );
                        }
                    }
                }
            }
        }

        /// <summary>
        /// Iterates through all peaks in a spectrum to find all potential isotopic envelopes.
        /// It does this by examining the spacing of peaks in the m/z domain
        /// e.g. for charge of 2, a peak at 200 m/z would result in a search for a peak at 200.5 and 201 m/z
        ///      if either is found, the process continues until SpectralParams.MaxConsecutiveMissedIsotopicPeaks number of consecutive
        ///      isotope peaks are missed
        /// Anything consistent with an isotopic envelope in a given charge state is stored in the dictionary
        /// </summary>
        /// <param name="spectrum"></param>
        /// <returns></returns>
        private Dictionary<int, List<List<int>>> FindPotentialEnvelopes(MzSpectrum spectrum)
        {

            // For each charge state (key) store the indices corresponding to every potential isotopic envelope (value)
            Dictionary<int, List<List<int>>> potentialEnvelopes = new();

            for (int charge = SpectralParams.MinAssumedChargeState; charge <= SpectralParams.MaxAssumedChargeState; charge++)
            {
                List<int> indicesOfKnownPeaks = new();

                // Spectrum Search Loop
                for (int i = 0; i < spectrum.Size; i++)
                {
                    if (indicesOfKnownPeaks.Contains(i))
                    {
                        continue;
                    }
                    List<int> envelope = new();
                    envelope.Add(i);

                    // Envelope Search Loop
                    for (int j = i + 1; j < spectrum.Size; j++)
                    {
                        if (PpmTolerance.Within(spectrum.XArray[j],
                                spectrum.XArray[envelope.Last()] + Constants.C13MinusC12 / charge))
                        {
                            envelope.Add(j);
                        }
                        else if (spectrum.XArray[j] > PpmTolerance.GetMaximumValue(spectrum.XArray[envelope.Last()] +
                                     (1 + SpectralParams.MaxConsecutiveMissedIsotopicPeaks) * Constants.C13MinusC12 / charge))
                        {
                            // exit the Envelope loop if we missed more consecutive isotopic peaks than were allowed
                            break;
                        }
                    }

                    if (envelope.Count > 1)
                    {
                        if (!potentialEnvelopes.ContainsKey(charge)) potentialEnvelopes.Add(charge, new());
                        potentialEnvelopes[charge].Add(envelope);
                        indicesOfKnownPeaks.AddRange(envelope);
                    }
                }
            }

            return potentialEnvelopes;
        }

    }
}
