// Copyright 2026 mzLib Contributors
// Licensed under the GNU Lesser General Public License v3.0

using MassSpectrometry.Dia;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace Development.Dia
{
    /// <summary>
    /// Parser for Koina/Prosit .msp spectral library files where the RT= field
    /// in the Comment line contains an iRT prediction, NOT an observed RT in minutes.
    ///
    /// This is distinct from KoinaMspParser (which is used by Phase23BenchmarkRunner
    /// and handles native-RT libraries with optional DIA-NN RT lookup).  Use THIS
    /// parser when:
    ///   - The library was generated by Prosit/Koina
    ///   - The Comment: RT= values are iRT units (typically 0–170 for CiRT scale)
    ///   - You need the calibrator to fit an iRT→RT slope (expected ~0.2 for 45-min gradient)
    ///
    /// Key differences from KoinaMspParser:
    ///   - RT= from Comment is assigned to IrtValue (not RetentionTime)
    ///   - RetentionTime is always null (Koina libraries have no observed RT)
    ///   - No rtLookup parameter — ground truth must never influence library iRT values
    ///   - isDecoy is always false here; caller sets IsDecoy=true for decoy MSP entries
    ///
    /// Koina .msp format:
    ///   Name: PEPTIDEK/2
    ///   MW: 1184.608784670464
    ///   Comment: Parent=1184.60878... RT=67.30357...
    ///   Num peaks: 64
    ///   147.076  0.05209  "y1^1/0ppm"
    ///   ...
    ///   Name: NEXTPEPTIDE/3     (next entry starts immediately, NO blank line)
    /// </summary>
    public static class KoinaIrtMspParser
    {
        /// <summary>
        /// Parse a Koina/Prosit .msp file into LibraryPrecursorInput objects.
        /// The RT= value in the Comment field is stored as IrtValue.
        /// RetentionTime is always null.
        /// </summary>
        /// <param name="mspPath">Path to the .msp file.</param>
        /// <param name="minIntensity">
        /// Minimum relative fragment intensity (0–1). Fragments below
        /// maxIntensity * minIntensity are discarded. Default 0.05 (5%).
        /// </param>
        public static List<LibraryPrecursorInput> Parse(
            string mspPath,
            float minIntensity = 0.05f)
        {
            if (!File.Exists(mspPath))
                throw new FileNotFoundException($"MSP file not found: {mspPath}");

            var results = new List<LibraryPrecursorInput>();
            int entriesParsed = 0;
            int entriesSkipped = 0;
            int totalFragments = 0;

            // Current entry state
            string currentSequence = null;
            int currentCharge = 0;
            double currentMW = 0;
            double currentMspIrt = -1;   // RT= from Comment — iRT units
            var mzList = new List<float>(128);
            var intList = new List<float>(128);
            bool inPeaks = false;

            using var reader = new StreamReader(mspPath);
            string line;

            while ((line = reader.ReadLine()) != null)
            {
                string trimmed = line.Trim();
                if (string.IsNullOrEmpty(trimmed)) continue;

                // A new "Name:" line means: finalize previous entry, start new one
                if (trimmed.StartsWith("Name:", StringComparison.OrdinalIgnoreCase))
                {
                    if (currentSequence != null && mzList.Count > 0)
                    {
                        var input = BuildPrecursorInput(
                            currentSequence, currentCharge, currentMW, currentMspIrt,
                            mzList, intList, minIntensity);
                        if (input.HasValue)
                        {
                            results.Add(input.Value);
                            totalFragments += input.Value.FragmentCount;
                            entriesParsed++;
                        }
                        else entriesSkipped++;
                    }

                    // Reset for new entry
                    currentMW = 0;
                    currentMspIrt = -1;
                    mzList.Clear();
                    intList.Clear();
                    inPeaks = false;
                    ParseNameLine(trimmed, out currentSequence, out currentCharge);
                    continue;
                }

                if (trimmed.StartsWith("MW:", StringComparison.OrdinalIgnoreCase))
                {
                    string val = trimmed.Substring(trimmed.IndexOf(':') + 1).Trim();
                    double.TryParse(val, NumberStyles.Float, CultureInfo.InvariantCulture, out currentMW);
                    continue;
                }

                if (trimmed.StartsWith("Comment:", StringComparison.OrdinalIgnoreCase))
                {
                    currentMspIrt = ParseFieldFromComment(trimmed, "RT=");
                    if (currentMW <= 0)
                        currentMW = ParseFieldFromComment(trimmed, "Parent=");
                    continue;
                }

                if (trimmed.StartsWith("Num peaks:", StringComparison.OrdinalIgnoreCase) ||
                    trimmed.StartsWith("Num Peaks:", StringComparison.OrdinalIgnoreCase))
                {
                    inPeaks = true;
                    continue;
                }

                if (inPeaks && trimmed.Length > 0 && (char.IsDigit(trimmed[0]) || trimmed[0] == '-'))
                {
                    ParsePeakLine(trimmed, mzList, intList);
                }
            }

            // Finalize last entry
            if (currentSequence != null && mzList.Count > 0)
            {
                var input = BuildPrecursorInput(
                    currentSequence, currentCharge, currentMW, currentMspIrt,
                    mzList, intList, minIntensity);
                if (input.HasValue)
                {
                    results.Add(input.Value);
                    totalFragments += input.Value.FragmentCount;
                    entriesParsed++;
                }
                else entriesSkipped++;
            }

            Console.WriteLine($"  MSP parsed: {entriesParsed:N0} entries, {totalFragments:N0} total fragments" +
                              (entriesSkipped > 0 ? $"  ({entriesSkipped} skipped)" : ""));

            return results;
        }

        // ═══════════════════════════════════════════════════════════════
        //  Line parsers
        // ═══════════════════════════════════════════════════════════════

        private static void ParseNameLine(string line, out string sequence, out int charge)
        {
            sequence = null;
            charge = 0;
            string value = line.Substring(line.IndexOf(':') + 1).Trim();
            int slashIdx = value.LastIndexOf('/');
            if (slashIdx > 0 && slashIdx < value.Length - 1 &&
                int.TryParse(value.Substring(slashIdx + 1), out charge))
            {
                string seqPart = value.Substring(0, slashIdx);
                sequence = System.Text.RegularExpressions.Regex.Replace(
                    seqPart, @"\[UNIMOD:(\d+)\]", "(UniMod:$1)",
                    System.Text.RegularExpressions.RegexOptions.IgnoreCase);
            }
        }

        private static double ParseFieldFromComment(string line, string fieldName)
        {
            string comment = line.Substring(line.IndexOf(':') + 1);
            int idx = comment.IndexOf(fieldName, StringComparison.OrdinalIgnoreCase);
            if (idx < 0) return -1;

            int start = idx + fieldName.Length;
            int end = start;
            while (end < comment.Length &&
                   (char.IsDigit(comment[end]) || comment[end] == '.' || comment[end] == '-' || comment[end] == 'e' || comment[end] == 'E' || comment[end] == '+'))
                end++;

            if (end > start &&
                double.TryParse(comment.Substring(start, end - start),
                    NumberStyles.Float, CultureInfo.InvariantCulture, out double val))
                return val;
            return -1;
        }

        private static void ParsePeakLine(string line, List<float> mzList, List<float> intList)
        {
            var parts = line.Split(new[] { '\t', ' ' }, StringSplitOptions.RemoveEmptyEntries);
            if (parts.Length >= 2 &&
                float.TryParse(parts[0], NumberStyles.Float, CultureInfo.InvariantCulture, out float mz) &&
                float.TryParse(parts[1], NumberStyles.Float, CultureInfo.InvariantCulture, out float intensity))
            {
                mzList.Add(mz);
                intList.Add(intensity);
            }
        }

        // ═══════════════════════════════════════════════════════════════
        //  Input builder
        // ═══════════════════════════════════════════════════════════════

        private static LibraryPrecursorInput? BuildPrecursorInput(
            string sequence, int charge, double mwOrMz, double mspIrt,
            List<float> mzList, List<float> intList,
            float minIntensity)
        {
            if (sequence == null || charge <= 0 || mzList.Count == 0) return null;

            // MW/Parent in Koina MSP is already the precursor m/z
            double precursorMz = mwOrMz;
            if (precursorMz <= 0) return null;

            // Filter fragments by relative intensity
            float maxInt = 0;
            for (int i = 0; i < intList.Count; i++)
                if (intList[i] > maxInt) maxInt = intList[i];

            float threshold = maxInt * minIntensity;
            var filtMz = new List<float>();
            var filtInt = new List<float>();
            for (int i = 0; i < mzList.Count; i++)
            {
                if (intList[i] > threshold && intList[i] > 0)
                {
                    filtMz.Add(mzList[i]);
                    filtInt.Add(intList[i]);
                }
            }
            if (filtMz.Count == 0) return null;

            var mzArr = filtMz.ToArray();
            var intArr = filtInt.ToArray();
            Array.Sort(mzArr, intArr);

            // RT= in the Koina MSP Comment is an iRT prediction (Prosit CiRT scale).
            // It is NOT an observed retention time in minutes.
            // Store it as IrtValue so the calibrator fits iRT→RT (slope ~0.2 for 45-min gradient).
            // RetentionTime is left null — Koina libraries have no observed RT.
            double? irt = mspIrt >= 0 ? (double?)mspIrt : null;

            return new LibraryPrecursorInput(
                sequence: sequence,
                precursorMz: precursorMz,
                chargeState: charge,
                retentionTime: null,
                isDecoy: false,
                fragmentMzs: mzArr,
                fragmentIntensities: intArr,
                irtValue: irt);
        }
    }
}