using MassSpectrometry;
using NUnit.Framework;
using Omics.Fragmentation;
using Omics.SpectralMatch.MslSpectralLibrary;
using Omics.SpectrumMatch;
using Readers.SpectralLibrary;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Test.MslSpectralLibrary;

/// <summary>
/// Ground-truth regression tests that use <c>syntheticTest2_PredictedLibrary.msp</c> as the
/// authoritative source of truth for the MSL binary format.
///
/// The MSP file was generated by DIA-NN / Koina (Prosit) from a known synthetic FASTA and
/// contains 42 precursors with a total of 968 fragment ions, all using standard terminal
/// ion annotations (b/y with optional charge superscripts). There are no internal ion
/// annotations in this file.
///
/// Test strategy:
/// <list type="number">
///   <item>
///     <see cref="OneTimeSetUp"/> reads the MSP via <see cref="SpectralLibrary"/>, saves every
///     spectrum to a temp .msl file via <see cref="MslLibrary.SaveFromLibrarySpectra"/>, then
///     reads the .msl back via <see cref="MslLibrary.Load"/> (full load) and
///     <see cref="MslLibrary.LoadIndexOnly"/> (index-only load) so both modes are available
///     to all tests.
///   </item>
///   <item>
///     Each test compares a property of the MSL-loaded data against the corresponding value
///     from the MSP-loaded data. This ensures that no data is lost or distorted by the
///     MSP → MSL conversion pipeline.
///   </item>
/// </list>
///
/// Regression baseline (hard-coded as constants to catch regressions immediately):
/// <list type="bullet">
///   <item><see cref="ExpectedPrecursorCount"/> = 42</item>
///   <item><see cref="ExpectedTotalFragments"/> = 968</item>
/// </list>
/// </summary>
[TestFixture]
public sealed class TestMslRegressionMsp
{
	// ─────────────────────────────────────────────────────────────────────────
	// Regression baseline constants
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Hard-coded precursor count from <c>syntheticTest2_PredictedLibrary.msp</c>.
	/// Each "Name:" line in the file represents one precursor; this value was confirmed
	/// by <c>grep -c "^Name:" syntheticTest2_PredictedLibrary.msp</c>.
	/// </summary>
	private const int ExpectedPrecursorCount = 42;

	/// <summary>
	/// Hard-coded total fragment count across all 42 precursors in the MSP file.
	/// Confirmed by summing the "Num peaks:" values: 968 total.
	/// </summary>
	private const int ExpectedTotalFragments = 968;

	/// <summary>
	/// m/z tolerance for precursor and fragment comparisons. Single-precision float32 is
	/// used for both fields in the binary format; rounding introduces at most ~5 × 10⁻⁵ Th
	/// error for values in the 100–2000 Th range.
	/// </summary>
	private const double MzTolerance = 1e-4;

	/// <summary>
	/// Tolerance for fragment intensity comparisons. Intensities are stored as float32 and
	/// normalized per precursor (max = 1.0) during the write step, so a very tight tolerance
	/// is appropriate for the normalized values.
	/// </summary>
	private const double IntensityTolerance = 1e-6;

	// ─────────────────────────────────────────────────────────────────────────
	// File paths
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// File name of the ground-truth MSP file.
	/// </summary>
	private const string MspFileName = "syntheticTest2_PredictedLibrary.msp";

	/// <summary>
	/// Path to the ground-truth MSP file, resolved by <see cref="FindMspFile"/>.
	/// The resolver walks up the directory tree from the NUnit output directory so that
	/// the test works both when the file is copied to the build output and when it lives
	/// in the source tree (the common case in this project).
	/// </summary>
	private static readonly string MspFilePath = FindMspFile();

	/// <summary>
	/// Locates <c>syntheticTest2_PredictedLibrary.msp</c> by searching candidate paths in
	/// priority order:
	/// <list type="number">
	///   <item>
	///     A <c>TestData</c> or <c>SpectralLibrary\SpectralLibraryData</c> subdirectory of
	///     the NUnit test output directory.
	///   </item>
	///   <item>
	///     The file sitting directly in any ancestor directory, up to 8 levels above the
	///     output directory.
	///   </item>
	///   <item>
	///     A <c>TestData</c>, <c>SpectralLibrary\SpectralLibraryData</c>, or
	///     <c>SpectralLibraryData</c> sibling of any ancestor directory.
	///   </item>
	/// </list>
	/// Returns the first existing path, or a sentinel that will be absent (causing
	/// <see cref="OneTimeSetUp"/> to skip gracefully with a clear message).
	/// </summary>
	private static string FindMspFile()
	{
		string outputDir = TestContext.CurrentContext.TestDirectory;

		// Sub-folder names to probe relative to any candidate directory
		string[] subfolders = new[]
		{
			"TestData",
			Path.Combine("SpectralLibrary", "SpectralLibraryData"),
			"SpectralLibraryData"
		};

		// Check all sub-folders relative to the output directory first
		foreach (string sub in subfolders)
		{
			string candidate = Path.Combine(outputDir, sub, MspFileName);
			if (File.Exists(candidate)) return candidate;
		}

		// Walk up the directory tree up to 8 levels
		string? dir = outputDir;
		for (int depth = 0; depth < 8 && dir != null; depth++)
		{
			// File sitting directly in this ancestor directory
			string direct = Path.Combine(dir, MspFileName);
			if (File.Exists(direct)) return direct;

			// Each sub-folder relative to this ancestor
			foreach (string sub in subfolders)
			{
				string sibling = Path.Combine(dir, sub, MspFileName);
				if (File.Exists(sibling)) return sibling;
			}

			dir = Path.GetDirectoryName(dir);
		}

		// Not found — return a sentinel so OneTimeSetUp can skip gracefully
		return Path.Combine(outputDir, "TestData", MspFileName);
	}

	/// <summary>
	/// Root directory for all temp files written by this fixture.
	/// Created in <see cref="OneTimeSetUp"/> and deleted in <see cref="OneTimeTearDown"/>.
	/// </summary>
	private static readonly string OutputDirectory =
		Path.Combine(Path.GetTempPath(), "MslRegressionTests");

	/// <summary>Path of the .msl file produced by the MSP → MSL conversion in SetUp.</summary>
	private static string MslPath => Path.Combine(OutputDirectory, "regression.msl");

	// ─────────────────────────────────────────────────────────────────────────
	// Shared state populated in OneTimeSetUp
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// All <see cref="LibrarySpectrum"/> objects read directly from the MSP file.
	/// This list is the ground truth against which all MSL-loaded data is compared.
	/// Populated once in <see cref="OneTimeSetUp"/>; read-only for all tests.
	/// </summary>
	private static List<LibrarySpectrum> _mspSpectra = new();

	/// <summary>
	/// The MSL library loaded in full-load mode from the file produced by the MSP → MSL
	/// conversion. Valid for the lifetime of the fixture; disposed in
	/// <see cref="OneTimeTearDown"/>.
	/// </summary>
	private static MslLibrary _fullLib = null!;

	/// <summary>
	/// The MSL library loaded in index-only mode from the same file.
	/// Valid for the lifetime of the fixture; disposed in <see cref="OneTimeTearDown"/>.
	/// </summary>
	private static MslLibrary _indexLib = null!;

	// ─────────────────────────────────────────────────────────────────────────
	// One-time setup / teardown
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Reads every spectrum from the MSP file, writes them to a temp .msl file, then opens
	/// the .msl in both full-load and index-only mode so all tests can use either path.
	/// Skips the entire fixture if the MSP file is not found (e.g. CI environment without
	/// test data), reporting a clear skip message.
	/// </summary>
	[OneTimeSetUp]
	public void OneTimeSetUp()
	{
		// Skip gracefully when the MSP test-data file is absent (e.g. shallow CI clone)
		if (!File.Exists(MspFilePath))
		{
			Assert.Ignore(
				$"Regression MSP file not found at '{MspFilePath}'. " +
				"Ensure TestData/syntheticTest2_PredictedLibrary.msp is present.");
			return;
		}

		Directory.CreateDirectory(OutputDirectory);

		// ── Step 1: Read all spectra from the MSP via SpectralLibrary ────────
		// SpectralLibrary.GetAllLibrarySpectra() enumerates every entry without requiring
		// individual TryGetSpectrum calls per sequence name.
		var mspLib = new SpectralLibrary(new List<string> { MspFilePath });
		_mspSpectra = mspLib.GetAllLibrarySpectra().ToList();
		mspLib.CloseConnections();

		// Guard: the MSP file must match the hard-coded baseline
		Assert.That(_mspSpectra.Count, Is.EqualTo(ExpectedPrecursorCount),
			$"MSP baseline has changed: expected {ExpectedPrecursorCount} precursors, " +
			$"got {_mspSpectra.Count}. Update ExpectedPrecursorCount if intentional.");

		// ── Step 2: Write all spectra to .msl ────────────────────────────────
		MslLibrary.SaveFromLibrarySpectra(MslPath, _mspSpectra);

		// ── Step 3: Open the .msl in both load modes ──────────────────────────
		_fullLib = MslLibrary.Load(MslPath);
		_indexLib = MslLibrary.LoadIndexOnly(MslPath);
	}

	/// <summary>
	/// Disposes both <see cref="MslLibrary"/> instances and deletes the temp output directory.
	/// </summary>
	[OneTimeTearDown]
	public void OneTimeTearDown()
	{
		_fullLib?.Dispose();
		_indexLib?.Dispose();

		if (Directory.Exists(OutputDirectory))
			Directory.Delete(OutputDirectory, recursive: true);
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Precursor-level regression tests
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// The number of precursors in the .msl file must equal the number of spectra read from
	/// the .msp file, which must equal the hard-coded baseline of 42.
	/// </summary>
	[Test]
	public void Regression_MspToMsl_PrecursorCount_Unchanged()
	{
		Assert.That(_fullLib.PrecursorCount, Is.EqualTo(ExpectedPrecursorCount));
	}

	/// <summary>
	/// For every spectrum in the MSP, the precursor m/z read back from the .msl must equal
	/// the MSP value within single-precision float tolerance (<see cref="MzTolerance"/>).
	///
	/// The lookup uses <see cref="MslLibrary.TryGetLibrarySpectrum"/> with the sequence and
	/// charge parsed from <see cref="LibrarySpectrum.Name"/> (format "SEQUENCE/CHARGE").
	/// </summary>
	[Test]
	public void Regression_MspToMsl_AllPrecursorMz_WithinTolerance()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);

			bool found = _fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? mslSpectrum);

			Assert.That(found, Is.True,
				$"Precursor '{mspSpectrum.Name}' not found in .msl");
			Assert.That(mslSpectrum!.PrecursorMz,
				Is.EqualTo(mspSpectrum.PrecursorMz).Within(MzTolerance),
				$"PrecursorMz mismatch for '{mspSpectrum.Name}'");
		}
	}

	/// <summary>
	/// For every spectrum in the MSP, each fragment m/z read back from the .msl must match
	/// the corresponding MSP fragment m/z within <see cref="MzTolerance"/>.
	///
	/// Fragments are matched positionally after sorting both lists by m/z ascending, which
	/// is the order guaranteed by the writer's normalization step.
	/// </summary>
	[Test]
	public void Regression_MspToMsl_AllFragmentMz_WithinTolerance()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);
			_fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? mslSpectrum);

			if (mslSpectrum is null) continue; // already caught by AllPrecursorMz test

			List<double> mspMzs = mspSpectrum.MatchedFragmentIons
				.Select(f => f.Mz).OrderBy(x => x).ToList();
			List<double> mslMzs = mslSpectrum.MatchedFragmentIons
				.Select(f => f.Mz).OrderBy(x => x).ToList();

			Assert.That(mslMzs.Count, Is.EqualTo(mspMzs.Count),
				$"Fragment count mismatch for '{mspSpectrum.Name}'");

			for (int i = 0; i < mspMzs.Count; i++)
			{
				Assert.That(mslMzs[i], Is.EqualTo(mspMzs[i]).Within(MzTolerance),
					$"Fragment [{i}] m/z mismatch for '{mspSpectrum.Name}': " +
					$"MSP={mspMzs[i]:F5} MSL={mslMzs[i]:F5}");
			}
		}
	}

	/// <summary>
	/// For every spectrum in the MSP, each fragment intensity read back from the .msl must
	/// match the corresponding MSP intensity within <see cref="IntensityTolerance"/>.
	///
	/// Note: the writer normalizes intensities so that the most intense fragment = 1.0. If
	/// the MSP intensities are already normalized (as they are for Prosit/Koina output), the
	/// comparison is direct. If not, both lists are normalized to their own maximum before
	/// comparison.
	/// </summary>
	[Test]
	public void Regression_MspToMsl_AllFragmentIntensities_WithinTolerance()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);
			_fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? mslSpectrum);

			if (mslSpectrum is null) continue;

			// Sort both by m/z ascending so intensities align positionally
			List<MatchedFragmentIon> mspSorted = mspSpectrum.MatchedFragmentIons
				.OrderBy(f => f.Mz).ToList();
			List<MatchedFragmentIon> mslSorted = mslSpectrum.MatchedFragmentIons
				.OrderBy(f => f.Mz).ToList();

			if (mspSorted.Count == 0 || mslSorted.Count != mspSorted.Count) continue;

			// Normalize each list independently (max = 1.0) to account for any
			// re-normalization applied by the writer
			double mspMax = mspSorted.Max(f => f.Intensity);
			double mslMax = mslSorted.Max(f => f.Intensity);

			for (int i = 0; i < mspSorted.Count; i++)
			{
				double mspNorm = mspMax > 0 ? mspSorted[i].Intensity / mspMax : 0;
				double mslNorm = mslMax > 0 ? mslSorted[i].Intensity / mslMax : 0;

				Assert.That(mslNorm, Is.EqualTo(mspNorm).Within(IntensityTolerance),
					$"Fragment [{i}] intensity mismatch for '{mspSpectrum.Name}': " +
					$"MSP_norm={mspNorm:F7} MSL_norm={mslNorm:F7}");
			}
		}
	}

	/// <summary>
	/// For every spectrum in the MSP, the sequence portion of
	/// <see cref="LibrarySpectrum.Name"/> (i.e. the part before "/") must be preserved
	/// exactly through the MSP → MSL → LibrarySpectrum pipeline.
	/// </summary>
	[Test]
	public void Regression_MspToMsl_SequenceNames_ExactMatch()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);

			bool found = _fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? mslSpectrum);

			Assert.That(found, Is.True,
				$"Sequence '{seq}' charge {charge} not found in .msl");
			Assert.That(mslSpectrum!.Name, Is.EqualTo(mspSpectrum.Name),
				$"Name mismatch: expected '{mspSpectrum.Name}', got '{mslSpectrum.Name}'");
		}
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Lookup regression tests
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// <see cref="MslLibrary.TryGetLibrarySpectrum"/> must successfully find every spectrum
	/// that was present in the MSP. A failure here indicates that a sequence/charge key was
	/// corrupted during the MSP → MSL conversion.
	/// </summary>
	[Test]
	public void Regression_MslTryGetLibrarySpectrum_FindsAllMspSpectra()
	{
		int found = 0;

		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);

			bool ok = _fullLib.TryGetLibrarySpectrum(seq, charge, out _);
			if (ok) found++;
		}

		Assert.That(found, Is.EqualTo(ExpectedPrecursorCount),
			$"Only {found}/{ExpectedPrecursorCount} MSP spectra could be found via TryGetLibrarySpectrum");
	}

	/// <summary>
	/// For every spectrum in the MSP, the fragment count returned by
	/// <see cref="MslLibrary.TryGetLibrarySpectrum"/> must exactly equal the number of
	/// fragment ions in the MSP spectrum. No fragments must be added or dropped.
	/// </summary>
	[Test]
	public void Regression_MslFragmentCount_ExactlyMatchesMsp()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);

			bool found = _fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? mslSpectrum);

			Assert.That(found, Is.True, $"'{mspSpectrum.Name}' not found in .msl");
			Assert.That(mslSpectrum!.MatchedFragmentIons.Count,
				Is.EqualTo(mspSpectrum.MatchedFragmentIons.Count),
				$"Fragment count mismatch for '{mspSpectrum.Name}': " +
				$"MSP={mspSpectrum.MatchedFragmentIons.Count} " +
				$"MSL={mslSpectrum.MatchedFragmentIons.Count}");
		}
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Index-only mode regression
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Fragments loaded via index-only mode (<see cref="MslLibrary.LoadIndexOnly"/>) must be
	/// identical to those loaded via full-load mode (<see cref="MslLibrary.Load"/>) for every
	/// spectrum in the MSP.
	///
	/// This test forces on-demand fragment loading for every precursor and verifies that the
	/// lazy disk read produces bit-for-bit identical m/z values to the pre-loaded full-load path.
	/// </summary>
	[Test]
	public void Regression_IndexOnlyMode_FragmentsMatchFullLoad()
	{
		foreach (LibrarySpectrum mspSpectrum in _mspSpectra)
		{
			(string seq, int charge) = ParseName(mspSpectrum.Name);

			_fullLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? fullSpectrum);
			_indexLib.TryGetLibrarySpectrum(seq, charge, out LibrarySpectrum? indexSpectrum);

			Assert.That(fullSpectrum, Is.Not.Null, $"Full-load did not find '{mspSpectrum.Name}'");
			Assert.That(indexSpectrum, Is.Not.Null, $"Index-only did not find '{mspSpectrum.Name}'");

			List<double> fullMzs = fullSpectrum!.MatchedFragmentIons.Select(f => f.Mz).OrderBy(x => x).ToList();
			List<double> indexMzs = indexSpectrum!.MatchedFragmentIons.Select(f => f.Mz).OrderBy(x => x).ToList();

			Assert.That(indexMzs.Count, Is.EqualTo(fullMzs.Count),
				$"Fragment count differs between load modes for '{mspSpectrum.Name}'");

			for (int i = 0; i < fullMzs.Count; i++)
			{
				Assert.That(indexMzs[i], Is.EqualTo(fullMzs[i]).Within(MzTolerance),
					$"Fragment [{i}] m/z differs between load modes for '{mspSpectrum.Name}'");
			}
		}
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Total fragment count regression
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// The sum of fragment counts across all 42 precursors in the .msl must equal the
	/// hard-coded baseline of 968 total fragments from the MSP file.
	/// </summary>
	[Test]
	public void Regression_TotalFragmentCount_MatchesBaseline()
	{
		int total = _fullLib.GetAllEntries()
							.Sum(e => e.Fragments.Count);

		Assert.That(total, Is.EqualTo(ExpectedTotalFragments),
			$"Total fragment count across all precursors: expected {ExpectedTotalFragments}, got {total}");
	}

	// ─────────────────────────────────────────────────────────────────────────
	// Private helpers
	// ─────────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Parses a <see cref="LibrarySpectrum.Name"/> string in the format "SEQUENCE/CHARGE"
	/// into its constituent sequence string and integer charge state.
	/// </summary>
	/// <param name="name">Name string, e.g. "MSTYNQK/2".</param>
	/// <returns>
	///   A tuple of (sequence, charge), e.g. ("MSTYNQK", 2).
	/// </returns>
	/// <exception cref="FormatException">
	///   Thrown when the name does not contain exactly one '/' separator or the charge
	///   portion is not a valid integer.
	/// </exception>
	private static (string sequence, int charge) ParseName(string name)
	{
		int slash = name.LastIndexOf('/');
		if (slash < 0)
			throw new FormatException($"LibrarySpectrum.Name '{name}' has no '/' separator");

		string seq = name[..slash];
		int charge = int.Parse(name[(slash + 1)..]);
		return (seq, charge);
	}
}