using CsvHelper.Configuration.Attributes;

namespace Readers;

/// <summary>
/// Represents a ProteinGroup generated by Chimerys (v4.3.0) when ran on the Msaid platform (v1.5.6)
/// </summary>
public class ChimerysProteinGroup
{
    [Name("PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] ProteinIds { get; set; }

    [Name("PROTEIN_GROUP_ID")]
    public int ProteinGroupId { get; set; }

    [Name("FASTA_HEADERS")]
    [TypeConverter(typeof(SemicolonDelimitedToStringArrayConverter))]
    public string[] FastaHeaders { get; set; }

    [Name("GENE_NAMES")]
    [TypeConverter(typeof(SemicolonDelimitedToStringArrayConverter))]
    public string[] GeneNames { get; set; }

    [Name("PROTEIN_IDENTIFIERS")]
    [TypeConverter(typeof(SemicolonDelimitedToStringArrayConverter))]
    public string[] ProteinIdentifiers { get; set; }

    [Name("TAXONOMY_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToStringArrayConverter))]
    public string[] TaxonomyIds { get; set; }

    [Name("ORGANISMS")]
    [TypeConverter(typeof(SemicolonDelimitedToStringArrayConverter))]
    public string[] Organisms { get; set; }

    [Name("RAW_FILE_NAME")]
    public string RawFileName { get; set; }

    [Name("SAMPLE_NAME")]
    public string SampleName { get; set; }

    [Name("GLOBAL_Q_VALUE")]
    public double GlobalQValue { get; set; }

    [Name("GLOBAL_SE_SCORE")]
    public double GlobalSearchEngineScore { get; set; }

    [Name("DECOY")]
    public bool IsDecoy { get; set; }

    [Name("PSM_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] PsmIds { get; set; }

    [Name("PRECURSOR_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] PrecursorIds { get; set; }

    [Name("MODIFIED_PEPTIDE_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] ModifiedPeptideIds { get; set; }

    [Name("PEPTIDE_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] PeptideIds { get; set; }

    [Name("COUNT_PSMS")]
    public int CountPsms { get; set; }

    [Name("COUNT_PRECURSORS")]
    public int CountPrecursors { get; set; }

    [Name("COUNT_MODIFIED_PEPTIDES")]
    public int CountModifiedPeptides { get; set; }

    [Name("COUNT_PEPTIDES")]
    public int CountPeptides { get; set; }

    [Name("QUANTIFICATION")]
    public double Quantification { get; set; }
}