using CsvHelper.Configuration.Attributes;

namespace Readers;

/// <summary>
/// Represents a Precursor generated by Chimerys (v4.3.0) when ran on the Msaid platform (v1.5.6)
/// </summary>
public class ChimerysPrecursor
{
    [Name("PRECURSOR_ID")]
    public int PrecursorId { get; set; }

    [Name("SEQUENCE")]
    public string BaseSequence { get; set; }

    [Name("MODIFIED_SEQUENCE")]
    public string ModifiedSequence { get; set; }

    [Name("MISSED_CLEAVAGES")]
    public int MissedCleavages { get; set; }

    [Name("MASS")]
    public double MonoisotopicMass { get; set; }

    [Name("PRECURSOR_CHARGE")]
    public int PrecursorCharge { get; set; }

    [Name("LENGTH")]
    public int Length { get; set; }

    [Name("M_Z")]
    public double Mz { get; set; }

    [Name("MIN_RETENTION_TIME")]
    public double MinRetentionTime { get; set; }

    [Name("MAX_RETENTION_TIME")]
    public double MaxRetentionTime { get; set; }

    [Name("MAX_SPECTRAL_ANGLE")]
    public double MaxSpectralAngle { get; set; }

    [Name("MAX_CTP")]
    public double MaxCtp { get; set; }

    [Name("IS_AMBIGUOUS")]
    public bool IsAmbiguous { get; set; }

    [Name("RAW_FILE_NAME")]
    public string RawFileName { get; set; }

    [Name("SAMPLE_NAME")]
    public string SampleName { get; set; }

    [Name("Q_VALUE")]
    public double QValue { get; set; }

    [Name("SE_SCORE")]
    public double SearchEngineScore { get; set; }

    [Name("PEP")]
    public double Pep { get; set; }

    [Name("GLOBAL_Q_VALUE")]
    public double GlobalQValue { get; set; }

    [Name("GLOBAL_SE_SCORE")]
    public double GlobalSearchEngineScore { get; set; }

    [Name("GLOBAL_PEP")]
    public double GlobalPep { get; set; }

    [Name("DECOY")]
    public bool IsDecoy { get; set; }

    [Name("IS_IDENTIFIED_BY_MBR")]
    public bool IsIdentifiedByMbr { get; set; }

    [Name("MODIFIED_PEPTIDE_ID")]
    public int ModifiedPeptideId { get; set; }

    [Name("PEPTIDE_ID")]
    public int PeptideId { get; set; }

    [Name("PSM_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] PsmIds { get; set; }

    [Name("POSITION_IN_PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] PositionInProteinIds { get; set; }

    [Name("PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] ProteinIds { get; set; }

    [Name("LOCALIZATION_SEQUENCE")]
    public string? LocalizationSequence { get; set; }

    [Name("LOCALIZATION_SCORE")]
    public string? LocalizationScore { get; set; }

    [Name("PROTEIN_SITES")]
    public string? ProteinSites { get; set; }

    [Name("COUNT_PSMS")]
    public int CountPsms { get; set; }

    [Name("QUANTIFICATION")]
    public double Quantification { get; set; }
}