using CsvHelper.Configuration.Attributes;

namespace Readers;

/// <summary>
/// Represents a Peptide generated by Chimerys (v4.3.0) when ran on the Msaid platform (v1.5.6)
/// </summary>
public class ChimerysPeptide
{
    [Name("PEPTIDE_ID")]
    public long PeptideId { get; set; }

    [Name("SEQUENCE")]
    public string BaseSequence { get; set; }

    [Name("LENGTH")]
    public int Length { get; set; }

    [Name("IS_AMBIGUOUS")]
    public bool IsAmbiguous { get; set; }

    [Name("RAW_FILE_NAME")]
    public string RawFileName { get; set; }

    [Name("SAMPLE_NAME")]
    public string SampleName { get; set; }

    [Name("Q_VALUE")]
    public double QValue { get; set; }

    [Name("SE_SCORE")]
    public double SearchEngineScore { get; set; }

    [Name("PEP")]
    public double Pep { get; set; }

    [Name("GLOBAL_Q_VALUE")]
    public double GlobalQValue { get; set; }

    [Name("GLOBAL_SE_SCORE")]
    public double GlobalSearchEngineScore { get; set; }

    [Name("GLOBAL_PEP")]
    public double GlobalPep { get; set; }

    [Name("DECOY")]
    public bool IsDecoy { get; set; }

    [Name("IS_IDENTIFIED_BY_MBR")]
    public bool IsIdentifiedByMbr { get; set; }

    [Name("PSM_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] PsmIds { get; set; }

    [Name("PRECURSOR_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] PrecursorIds { get; set; }

    [Name("MODIFIED_PEPTIDE_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] ModifiedPeptideIds { get; set; }

    [Name("POSITION_IN_PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] PositionInProteinIds { get; set; }

    [Name("PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] ProteinIds { get; set; }

    [Name("COUNT_PSMS")]
    public int CountPsms { get; set; }

    [Name("COUNT_PRECURSORS")]
    public int CountPrecursors { get; set; }

    [Name("COUNT_MODIFIED_PEPTIDES")]
    public int CountModifiedPeptides { get; set; }

    [Name("QUANTIFICATION")]
    public double Quantification { get; set; }





}