using CsvHelper.Configuration.Attributes;

namespace Readers;

/// <summary>
/// Represents a PSM generated by Chimerys (v4.3.0) when ran on the Msaid platform (v1.5.6)
/// </summary>
public class ChimerysPsm
{
    [Name("PSM_ID")]
    public long PsmId { get; set; }

    [Name("SEQUENCE")]
    public string BaseSequence { get; set; }

    [Name("MODIFIED_SEQUENCE")]
    public string ModifiedSequence { get; set; }

    [Name("MISSED_CLEAVAGES")]
    public int MissedCleavages { get; set; }

    [Name("MASS")]
    public double MonoisotopicMass { get; set; }

    [Name("PRECURSOR_CHARGE")]
    public int PrecursorCharge { get; set; }

    [Name("LENGTH")]
    public int Length { get; set; }

    [Name("M_Z")]
    public double Mz { get; set; }

    [Name("SCAN_NUMBER_IN_FILE")]
    public int OneBasedScanNumber { get; set; }

    [Name("RETENTION_TIME")]
    public double RetentionTime { get; set; }

    [Name("RETENTION_TIME_PREDICTION")]
    public double RetentionTimePrediction { get; set; }

    /// <summary>
    /// The coefficient is the output of our deconvolution function and can be understood
    /// as the summed MS2 intensity of all matched fragments for this peptide.
    /// </summary>
    [Name("COEFF")]
    public double Coeff { get; set; }

    [Name("SPECTRAL_ANGLE")]
    public double SpectralAngle { get; set; }

    /// <summary>
    /// The CTP score combines the spectral angle and the ratio of predicted and matched fragment ions.
    /// It ranged from 0-1, with 1 being best.
    /// </summary>
    [Name("CTP")]
    public double Ctp { get; set; }

    [Name("MATCHED_PEAKS")]
    public int MatchedFragmentIonCount { get; set; }

    /// <summary>
    /// Top peaks are the highest peaks of the prediction.
    /// Minimum three out of the five highest predicted peaks must be matched.
    /// Number of top peaks matched until maximum two peaks are missed.
    /// </summary>
    [Name("TOP_PEAKS_SHARED")]
    public int TopPeaksShared { get; set; }

    [Name("IS_AMBIGUOUS")]
    public bool IsAmbiguous { get; set; }

    [Name("RAW_FILE_NAME")]
    public string RawFileName { get; set; }

    [Name("SAMPLE_NAME")]
    public string SampleName { get; set; }

    [Name("Q_VALUE")]
    public double QValue { get; set; }

    [Name("SE_SCORE")]
    public double SearchEngineScore { get; set; }

    [Name("PEP")]
    public double Pep { get; set; }

    [Name("DECOY")]
    public bool IsDecoy { get; set; }

    [Name("PRECURSOR_ID")]
    public long PrecursorId { get; set; }

    [Name("MODIFIED_PEPTIDE_ID")]
    public long ModifiedPeptideId { get; set; }

    [Name("PEPTIDE_ID")]
    public long PeptideId { get; set; }

    /// <summary>
    /// Starting amino acid position of this peptide in its Protein.
    /// </summary>
    [Name("POSITION_IN_PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToIntegerArrayConverter))]
    public int[] PositionInProteinIds { get; set; }

    /// <summary>
    /// One or several numeric protein identifiers for the precursor
    /// </summary>
    [Name("PROTEIN_IDS")]
    [TypeConverter(typeof(SemicolonDelimitedToLongArrayConverter))]
    public long[] ProteinIds { get; set; }

    [Name("LOCALIZATION_SEQUENCE")]
    public string? LocalizationSequence { get; set; }

    [Name("LOCALIZATION_SCORE")]
    public string? LocalizationScore { get; set; }

    [Name("PROTEIN_SITES")]
    public string? ProteinSites { get; set; }

}