using System;
using System.Collections.Generic;
using System.Linq;

namespace MassSpectrometry
{
    /// <summary>
    /// Computes target-decoy q-values for <see cref="IsotopicEnvelope"/> scores
    /// produced by <see cref="DeconvolutionScorer"/>.
    ///
    /// The q-value definition follows Käll et al. (2008) with the +1 correction
    /// from Elias &amp; Gygi (2007):
    ///   q(t) = (#{decoys with score ≥ t} + 1) / #{targets with score ≥ t}
    /// clamped to [0, 1] and enforced to be monotonically non-decreasing as the
    /// score threshold decreases (i.e., higher-scoring targets have q-values ≤
    /// lower-scoring targets).
    ///
    /// Decoy envelopes are generated by
    /// <see cref="Deconvoluter.DeconvoluteWithDecoys"/> using a shifted isotope
    /// distance (0.9444 Da) that does not correspond to any real molecular species.
    /// </summary>
    public static class DeconvolutionQValueCalculator
    {
        // ── Primary overload: operates on raw score arrays ────────────────────

        /// <summary>
        /// Assigns q-values to target envelopes given their scores and the decoy
        /// score distribution.
        /// </summary>
        /// <param name="targetScores">
        /// Generic scores (from <see cref="DeconvolutionScorer.ScoreEnvelope"/>) for
        /// each target envelope. Order does not matter — q-values are returned in the
        /// same order as the input.
        /// </param>
        /// <param name="decoyScores">
        /// Scores from the decoy deconvolution pass (same scorer, different envelopes).
        /// </param>
        /// <returns>
        /// Array of q-values in the same order as <paramref name="targetScores"/>.
        /// All values are in [0, 1]. Higher-scoring targets have lower or equal
        /// q-values than lower-scoring targets.
        /// </returns>
        public static double[] AssignQValues(
            IReadOnlyList<double> targetScores,
            IReadOnlyList<double> decoyScores)
        {
            int nTargets = targetScores.Count;
            if (nTargets == 0)
                return Array.Empty<double>();

            // Edge case: no decoys → FDR is 0 everywhere
            if (decoyScores.Count == 0)
                return new double[nTargets]; // all zeros

            // ── Step 1: sort targets by score descending (highest score first) ─
            // Keep track of original indices so we can return in input order.
            int[] order = Enumerable.Range(0, nTargets)
                .OrderByDescending(i => targetScores[i])
                .ToArray();

            double[] sortedTargetScores = order.Select(i => targetScores[i]).ToArray();

            // ── Step 2: sort decoy scores descending for efficient counting ────
            double[] sortedDecoys = decoyScores.OrderByDescending(s => s).ToArray();

            // ── Step 3: compute raw q-values at each target score threshold ────
            // Walk targets from highest to lowest score; advance the decoy pointer
            // to count how many decoys are ≥ the current threshold.
            double[] rawQ = new double[nTargets];
            int decoyPointer = 0;

            for (int i = 0; i < nTargets; i++)
            {
                double threshold = sortedTargetScores[i];

                // Count decoys with score >= threshold
                while (decoyPointer < sortedDecoys.Length
                       && sortedDecoys[decoyPointer] >= threshold)
                    decoyPointer++;

                int nDecoysAbove  = decoyPointer;
                int nTargetsAbove = i + 1; // targets are sorted; indices 0..i are all >= threshold

                // +1 correction per Elias & Gygi (2007) / Käll et al. (2008):
                // avoids 0% FDR estimates and accounts for expected false targets.
                double q = (double)(nDecoysAbove + 1) / nTargetsAbove;

                rawQ[i] = Math.Max(0.0, Math.Min(1.0, q));
            }

            // ── Step 4: enforce monotonicity ──────────────────────────────────
            // Sweep from lowest score (end of array) to highest score (start).
            // Each q-value must be ≤ the q-value of any lower-scoring target.
            // Running minimum from the bottom up ensures this.
            double runningMin = 1.0;
            for (int i = nTargets - 1; i >= 0; i--)
            {
                runningMin = Math.Min(runningMin, rawQ[i]);
                rawQ[i]    = runningMin;
            }

            // ── Step 5: map back to original input order ──────────────────────
            double[] result = new double[nTargets];
            for (int i = 0; i < nTargets; i++)
                result[order[i]] = rawQ[i];

            return result;
        }

        // ── Convenience overload: operates on (envelope, score) pairs ─────────

        /// <summary>
        /// Assigns q-values to target envelope-score pairs given the decoy score
        /// distribution, and returns triples of (envelope, score, qValue).
        /// </summary>
        /// <param name="targetPairs">
        /// Target envelope-score pairs from
        /// <see cref="DeconvolutionScorer.ScoreEnvelopes"/>. Enumerated in full.
        /// </param>
        /// <param name="decoyPairs">
        /// Decoy envelope-score pairs. Only the scores are used for FDR estimation.
        /// Enumerated in full.
        /// </param>
        public static IEnumerable<(IsotopicEnvelope Envelope, double Score, double QValue)>
            AssignQValues(
                IEnumerable<(IsotopicEnvelope Envelope, double Score)> targetPairs,
                IEnumerable<(IsotopicEnvelope Envelope, double Score)> decoyPairs)
        {
            var targets = targetPairs.ToList();
            var decoys  = decoyPairs.ToList();

            double[] targetScores = targets.Select(p => p.Score).ToArray();
            double[] decoyScores  = decoys.Select(p => p.Score).ToArray();

            double[] qValues = AssignQValues(targetScores, decoyScores);

            for (int i = 0; i < targets.Count; i++)
                yield return (targets[i].Envelope, targets[i].Score, qValues[i]);
        }

        // ── Score threshold for a target FDR ─────────────────────────────────

        /// <summary>
        /// Returns the minimum score such that the estimated q-value is at or
        /// below <paramref name="maxFdr"/>.
        /// </summary>
        /// <param name="targetScores">Target scores (same input as <see cref="AssignQValues"/>).</param>
        /// <param name="decoyScores">Decoy scores.</param>
        /// <param name="maxFdr">Maximum acceptable q-value. Default: 0.01 (1% FDR).</param>
        /// <returns>
        /// The minimum score threshold that achieves the requested FDR.
        /// Returns <c>1.0</c> if no score achieves the FDR (i.e. even the best target
        /// has q-value > <paramref name="maxFdr"/>).
        /// Returns <c>0.0</c> if all targets achieve the FDR.
        /// </returns>
        public static double GetFdrThreshold(
            IReadOnlyList<double> targetScores,
            IReadOnlyList<double> decoyScores,
            double maxFdr = 0.01)
        {
            if (targetScores.Count == 0)
                return 1.0;

            double[] qValues = AssignQValues(targetScores, decoyScores);

            // Find the lowest score for which the q-value is <= maxFdr
            double threshold = 1.0;
            for (int i = 0; i < targetScores.Count; i++)
            {
                if (qValues[i] <= maxFdr)
                    threshold = Math.Min(threshold, targetScores[i]);
            }

            return threshold;
        }
    }
}
